#!/usr/bin/env bash
# Reproduce the whole experiment from a clean clone.
#
#   ./run_all.sh
#
# Pins the numeric environment to single-threaded so re-derivation is bit-exact
# (see SCOPE.md). Produces runs/record.json and writes evidence to RESULTS.md.
set -euo pipefail
cd "$(dirname "$0")"

# Determinism-critical: pin BLAS threads BEFORE python imports numpy.
export OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 VECLIB_MAXIMUM_THREADS=1 MKL_NUM_THREADS=1

LOG=RESULTS.md
{
  echo "# RESULTS (generated by run_all.sh)"
  echo
  echo "Environment pin: OPENBLAS/OMP/VECLIB/MKL_NUM_THREADS=1"
  echo "Python: $(python3 --version 2>&1) | NumPy: $(python3 -c 'import numpy;print(numpy.__version__)')"
  echo
  echo '## 1. Gradient check (training engine is verified, not assumed)'
  echo '```'
  python3 tests/gradcheck.py
  echo '```'
  echo
  echo '## 2. Capture a run'
  echo '```'
  python3 train.py --out runs/record.json
  echo '```'
  echo
  echo '## 3. Verify the clean record (expect VERIFIED)'
  echo '```'
  python3 verify.py runs/record.json
  echo '```'
  echo
  echo '## 4. Negative controls (each tampering must be caught)'
  echo '```'
  python3 tests/negative_controls.py
  echo '```'
  echo
  echo '## 5. Determinism probe (same code+config, different thread counts)'
  echo '```'
  python3 tests/determinism_probe.py
  echo '```'
} 2>&1 | tee "$LOG"

echo
echo "wrote $LOG"
